apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
spec:
  type: NodePort
  selector:
    app: simple-web-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30090
